# Generated by Django 2.0.5 on 2018-05-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=128)),
                ('claimant', models.CharField(max_length=128)),
                ('registration_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.CharField(max_length=128)),
                ('detail', models.CharField(max_length=1024)),
            ],
        ),
    ]
