# Generated by Django 2.0.5 on 2018-05-29 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='registration_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
